theme: minima
title: Kole Kendrick's Video Game Museum
author: Kole Kendrick
email: Viktor.kendrick@Gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Here will be varius games that Kole Kendrick has played, and his thoughts about the games.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
